"""Stage 2 data source: Existing Solution Discovery.

This is a curated, static knowledge base of well-known real-world
products per domain, used for offline similarity/gap analysis without
depending on a live web-search API or key. It is intentionally
editable -- teams can grow this list over time (that's the natural
place to plug in a real search API later, see llm_client.py).

Each entry uses general, widely-known facts about the product's
purpose (not time-sensitive figures like pricing or user counts).
"""

KNOWLEDGE_BASE = {
    "Education": [
        {"name": "Khan Academy", "description": "Free video lessons and practice exercises covering school-level subjects for self-paced learning.",
         "key_features": ["video lessons", "practice exercises", "progress tracking"],
         "limitations": ["not localized for regional curricula", "limited live doubt-solving", "no offline-first mode for low-connectivity areas"]},
        {"name": "Duolingo", "description": "Gamified language-learning app using short daily lessons and streaks.",
         "key_features": ["gamification", "spaced repetition", "streaks"],
         "limitations": ["focused only on language learning", "limited depth for advanced learners", "no human tutor access"]},
        {"name": "BYJU'S", "description": "Video-based learning app for K-12 students with animated concept explanations.",
         "key_features": ["animated videos", "adaptive practice", "live classes"],
         "limitations": ["subscription cost barrier", "less effective for hands-on/practical skills", "heavy content, less community/peer learning"]},
        {"name": "Google Classroom", "description": "Classroom management tool for assignments, grading, and teacher-student communication.",
         "key_features": ["assignment distribution", "grading", "class communication"],
         "limitations": ["not a content/tutoring platform itself", "requires teacher setup effort", "limited built-in analytics on learning gaps"]},
        {"name": "Coursera", "description": "University and industry-partnered online courses with certificates.",
         "key_features": ["structured courses", "certificates", "peer assignments"],
         "limitations": ["aimed at adult/higher-ed learners", "less suited to school-level curricula", "cost for certificates"]},
    ],
    "Healthcare": [
        {"name": "Practo", "description": "Platform to search doctors, book appointments, and consult online.",
         "key_features": ["doctor search", "appointment booking", "teleconsultation"],
         "limitations": ["limited rural doctor coverage", "no proactive health monitoring", "language support varies"]},
        {"name": "1mg", "description": "Online pharmacy and lab test booking platform with medicine information.",
         "key_features": ["medicine ordering", "lab test booking", "drug info"],
         "limitations": ["delivery delays in remote areas", "not a diagnosis tool", "limited chronic-care follow-up"]},
        {"name": "Apollo 24|7", "description": "Hospital-network app for consultations, records, and pharmacy in one place.",
         "key_features": ["e-consultation", "digital health records", "pharmacy"],
         "limitations": ["tied to one hospital network's ecosystem", "cost of consultations", "limited offline access to records"]},
        {"name": "Ada Health", "description": "AI symptom-checker app that asks guided questions to suggest possible conditions.",
         "key_features": ["symptom checker", "condition suggestions", "care guidance"],
         "limitations": ["not a diagnosis, guidance only", "limited regional disease-pattern tuning", "no direct doctor connect"]},
        {"name": "CureFit (Cult.fit)", "description": "Fitness and wellness app combining workouts, diet plans, and doctor consults.",
         "key_features": ["fitness classes", "diet plans", "doctor consults"],
         "limitations": ["urban-centric", "subscription pricing", "less focused on chronic illness management"]},
    ],
    "Agriculture": [
        {"name": "Plantix", "description": "AI app that identifies crop diseases and pests from a photo of the plant.",
         "key_features": ["image-based disease detection", "treatment tips", "community forum"],
         "limitations": ["needs decent camera/internet", "limited crop coverage in some regions", "no direct market linkage"]},
        {"name": "Kisan Suvidha", "description": "Government app offering weather, market prices, and farming advisories.",
         "key_features": ["weather updates", "mandi prices", "crop advisory"],
         "limitations": ["generic advisory, not personalized to a specific field", "UI/UX often cited as clunky", "limited two-way farmer support"]},
        {"name": "DeHaat", "description": "Full-stack agri platform connecting farmers to inputs, advisory, and market for produce.",
         "key_features": ["input marketplace", "farm advisory", "produce selling"],
         "limitations": ["operates through local agents in specific regions", "not fully self-serve everywhere", "onboarding effort for new farmers"]},
        {"name": "AgriApp", "description": "Marketplace and advisory app for buying farm inputs and getting crop guidance.",
         "key_features": ["input marketplace", "expert advisory", "crop calendar"],
         "limitations": ["regional availability limits", "less real-time field-sensor data", "advisory is generic, not IoT-driven"]},
        {"name": "CropIn", "description": "Farm-management SaaS for agribusinesses using satellite and IoT data.",
         "key_features": ["satellite crop monitoring", "farm analytics", "traceability"],
         "limitations": ["built for agribusinesses/enterprises, not individual smallholders", "cost prohibitive for small farms", "needs technical onboarding"]},
    ],
    "Environment & Sustainability": [
        {"name": "Too Good To Go", "description": "App connecting users to unsold food from restaurants/stores at a discount to cut food waste.",
         "key_features": ["surplus food listings", "discounted pickup", "waste tracking"],
         "limitations": ["depends on partner restaurant density in an area", "not focused on household waste", "limited in smaller towns"]},
        {"name": "Ecosia", "description": "Search engine that uses ad revenue to fund tree planting.",
         "key_features": ["search + tree planting", "impact transparency reports"],
         "limitations": ["passive impact model, not an active sustainability tool", "no personal footprint tracking"]},
        {"name": "AirVisual (IQAir)", "description": "Real-time air-quality tracking app with forecasts and health recommendations.",
         "key_features": ["real-time AQI", "forecasts", "health tips"],
         "limitations": ["sensor density varies by city", "no personalized exposure-reduction plan", "limited action/community features"]},
        {"name": "JouleBug", "description": "App that gamifies small sustainable habits like saving energy or reducing waste.",
         "key_features": ["habit challenges", "gamification", "community leaderboard"],
         "limitations": ["self-reported actions, not verified", "engagement drops without novelty", "limited India-specific content"]},
        {"name": "iRecycle", "description": "Directory app to find nearby recycling centers for specific material types.",
         "key_features": ["recycling center locator", "material-specific search"],
         "limitations": ["directory data can go stale", "no pickup/logistics feature", "limited coverage outside the US"]},
    ],
    "Fintech & Payments": [
        {"name": "PhonePe", "description": "UPI-based payments app for transfers, bill payments, and merchant checkout.",
         "key_features": ["UPI transfers", "bill payments", "merchant QR payments"],
         "limitations": ["transaction-focused, weak budgeting/analytics", "no lending/credit-building tools", "customer support delays reported"]},
        {"name": "Paytm", "description": "Payments and financial services super-app covering wallet, UPI, and bill payments.",
         "key_features": ["wallet", "UPI", "bill payments", "ticket booking"],
         "limitations": ["feature bloat can hurt usability", "not focused on personal finance planning", "ad-heavy interface"]},
        {"name": "CRED", "description": "Credit-card bill payment app that rewards on-time payments with points.",
         "key_features": ["credit card bill pay", "reward points", "credit score tracking"],
         "limitations": ["only useful for credit-card holders", "reward redemption limited to partner brands", "not for broader budgeting"]},
        {"name": "Google Pay", "description": "UPI payments app for peer transfers and bill payments with simple UI.",
         "key_features": ["UPI transfers", "bill payments", "transaction history"],
         "limitations": ["no budgeting or savings-goal features", "no lending products", "limited financial literacy content"]},
        {"name": "Razorpay", "description": "Payment gateway and business banking suite for merchants and startups.",
         "key_features": ["payment gateway", "business banking", "invoicing"],
         "limitations": ["built for businesses, not individual consumers", "requires KYC/business onboarding", "not a personal-finance tool"]},
    ],
    "Transportation & Logistics": [
        {"name": "Ola", "description": "Ride-hailing app for cabs and auto-rickshaws in Indian cities.",
         "key_features": ["ride booking", "fare estimate", "multiple vehicle types"],
         "limitations": ["surge pricing frustration", "driver availability varies by city", "limited rural coverage"]},
        {"name": "Porter", "description": "On-demand app for booking mini-trucks and two-wheelers for goods transport.",
         "key_features": ["goods transport booking", "multiple vehicle sizes", "live tracking"],
         "limitations": ["city-limited availability", "less suited for long-haul freight", "pricing can vary with demand"]},
        {"name": "Delhivery", "description": "Logistics and courier platform for e-commerce shipment delivery and tracking.",
         "key_features": ["shipment tracking", "warehousing", "last-mile delivery"],
         "limitations": ["built for business/e-commerce shippers, not individuals", "tracking granularity varies by area", "support responsiveness varies"]},
        {"name": "Rapido", "description": "Bike-taxi app for quick point-to-point rides in congested cities.",
         "key_features": ["bike-taxi booking", "fare estimate", "quick pickup"],
         "limitations": ["weather-dependent reliability", "limited to two-wheeler capacity", "safety perception concerns for some users"]},
        {"name": "Uber", "description": "Global ride-hailing app for cabs with fare estimates and driver ratings.",
         "key_features": ["ride booking", "fare estimate", "ratings"],
         "limitations": ["surge pricing", "limited presence in smaller towns", "no goods-transport focus"]},
    ],
    "Safety & Security": [
        {"name": "112 India", "description": "National emergency response app for police, fire, and medical emergencies.",
         "key_features": ["one-tap SOS", "location sharing", "multi-service emergency dispatch"],
         "limitations": ["response time depends on local infra", "limited proactive/preventive features", "awareness of the app is low in some areas"]},
        {"name": "bSafe", "description": "Personal safety app with SOS alerts, live streaming, and fake-call features.",
         "key_features": ["SOS alert", "live location streaming", "fake call trigger"],
         "limitations": ["relies on guardians being reachable/responsive", "battery drain from live streaming", "subscription for full features"]},
        {"name": "Life360", "description": "Family location-sharing and safety-alert app.",
         "key_features": ["location sharing", "driving reports", "crash detection"],
         "limitations": ["privacy concerns among tracked users", "not designed for public/stranger-danger scenarios", "premium features paywalled"]},
        {"name": "Himmat Plus", "description": "Delhi Police women-safety app for SOS alerts monitored by police control room.",
         "key_features": ["SOS to police control room", "audio/video evidence capture", "location tracking"],
         "limitations": ["limited to specific city jurisdiction", "depends on local police responsiveness", "low public awareness"]},
        {"name": "Raksha", "description": "Women-safety app offering SOS alerts to pre-selected emergency contacts.",
         "key_features": ["SOS to contacts", "location sharing", "silent alarm"],
         "limitations": ["depends on contacts being available", "no direct law-enforcement integration in most versions", "limited community/reporting features"]},
    ],
    "Accessibility & Inclusion": [
        {"name": "Be My Eyes", "description": "Connects blind/low-vision users to sighted volunteers via live video call for visual assistance.",
         "key_features": ["live video assistance", "volunteer network", "AI-assisted description option"],
         "limitations": ["depends on volunteer availability", "needs stable internet for video", "not built for offline use"]},
        {"name": "Seeing AI", "description": "App that narrates the world for blind users -- text, objects, people, currency.",
         "key_features": ["text-to-speech reading", "object recognition", "currency recognition"],
         "limitations": ["accuracy varies in poor lighting", "limited to what the camera captures", "not multilingual for all regional languages"]},
        {"name": "Google Lookout", "description": "App that identifies objects, text, and scenes to assist low-vision users.",
         "key_features": ["scene description", "text scanning", "food label recognition"],
         "limitations": ["Android-focused feature set", "regional language support limited", "needs decent camera quality"]},
        {"name": "Voice Dream Reader", "description": "Text-to-speech reading app for users with visual or reading disabilities.",
         "key_features": ["text-to-speech", "adjustable reading speed", "multiple file format support"],
         "limitations": ["paid app", "less useful for live/real-world scene understanding", "limited Indian-language voices"]},
        {"name": "Sound Amp", "description": "App that amplifies ambient sound for users with hearing difficulty via headphones.",
         "key_features": ["real-time sound amplification", "adjustable frequency"],
         "limitations": ["not a substitute for hearing aids", "battery/headphone dependency", "no sign-language support"]},
    ],
    "Productivity & Work": [
        {"name": "Notion", "description": "All-in-one workspace for notes, docs, and light project tracking.",
         "key_features": ["notes/docs", "databases", "templates"],
         "limitations": ["steep learning curve for teams", "can get slow with large workspaces", "offline support is limited"]},
        {"name": "Trello", "description": "Kanban-board based task and project management tool.",
         "key_features": ["kanban boards", "checklists", "automation (Butler)"],
         "limitations": ["weak for complex/dependency-based project plans", "reporting features are basic", "gets cluttered on large projects"]},
        {"name": "Slack", "description": "Team messaging platform with channels and integrations.",
         "key_features": ["channels", "direct messaging", "app integrations"],
         "limitations": ["message overload in busy workspaces", "not a task-management tool by itself", "cost scales with team size"]},
        {"name": "Todoist", "description": "Task manager with natural-language due dates and productivity tracking.",
         "key_features": ["task lists", "natural-language scheduling", "productivity streaks"],
         "limitations": ["limited team-collaboration depth", "no built-in docs/wiki", "advanced features are paywalled"]},
        {"name": "ClickUp", "description": "Project-management suite combining tasks, docs, goals, and dashboards.",
         "key_features": ["tasks", "docs", "dashboards", "goal tracking"],
         "limitations": ["feature overload/complex UI", "performance can lag with heavy use", "steep onboarding for new teams"]},
    ],
    "E-commerce & Retail": [
        {"name": "Flipkart", "description": "General e-commerce marketplace for a wide range of product categories.",
         "key_features": ["marketplace listings", "cart/checkout", "logistics network"],
         "limitations": ["highly competitive/generic category, hard to differentiate", "seller quality varies", "return/refund friction reported"]},
        {"name": "Meesho", "description": "Social-commerce marketplace focused on affordable products via resellers.",
         "key_features": ["reseller model", "low-cost listings", "social sharing tools"],
         "limitations": ["product quality inconsistency", "trust/verification challenges", "thin margins for resellers"]},
        {"name": "Amazon", "description": "Global e-commerce marketplace with extensive logistics and same-day delivery in many areas.",
         "key_features": ["marketplace", "fast delivery", "reviews/ratings"],
         "limitations": ["dominant scale makes niche differentiation hard", "seller competition is intense", "less personalized for hyper-local needs"]},
        {"name": "Myntra", "description": "Fashion and lifestyle e-commerce platform.",
         "key_features": ["fashion catalog", "try-and-buy", "style recommendations"],
         "limitations": ["category-specific (fashion only)", "sizing/fit issues common complaint", "returns logistics cost"]},
        {"name": "Zepto", "description": "Quick-commerce app promising grocery delivery within minutes.",
         "key_features": ["ultra-fast delivery", "dark-store fulfillment", "grocery catalog"],
         "limitations": ["only viable in dense urban areas", "thin margins on quick delivery", "limited catalog vs full marketplaces"]},
    ],
    "Mental Health & Wellbeing": [
        {"name": "Wysa", "description": "AI chatbot offering CBT-based emotional support and coping techniques.",
         "key_features": ["AI chat support", "CBT exercises", "mood tracking"],
         "limitations": ["not a replacement for a licensed therapist", "limited crisis-response depth", "engagement can fade over time"]},
        {"name": "Headspace", "description": "Guided meditation and mindfulness app.",
         "key_features": ["guided meditations", "sleep sounds", "focus exercises"],
         "limitations": ["subscription cost", "limited India-specific/regional-language content", "not clinical support"]},
        {"name": "Calm", "description": "Meditation and sleep-focused wellness app with guided sessions.",
         "key_features": ["sleep stories", "guided meditation", "breathing exercises"],
         "limitations": ["subscription cost", "generic content, not personalized to specific conditions", "no therapist connect"]},
        {"name": "YourDOST", "description": "Online counseling platform connecting users to therapists and coaches.",
         "key_features": ["therapist matching", "chat/video counseling", "anonymous support"],
         "limitations": ["cost per session", "availability of specialists varies by language", "less self-guided/preventive tooling"]},
        {"name": "InnerHour", "description": "Self-help mental wellness app with structured CBT-based programs.",
         "key_features": ["structured self-help programs", "mood tracker", "journaling"],
         "limitations": ["self-guided only unless upgraded", "limited crisis support", "regional language depth varies"]},
    ],
    "Governance & Civic Tech": [
        {"name": "UMANG", "description": "Unified government services app aggregating multiple central/state e-services.",
         "key_features": ["multi-service aggregation", "Aadhaar-linked services", "multilingual support"],
         "limitations": ["UX inconsistency across bundled services", "not all state services integrated", "occasional server downtime"]},
        {"name": "DigiLocker", "description": "Digital document wallet for storing and verifying government-issued documents.",
         "key_features": ["document storage", "e-verification", "Aadhaar linkage"],
         "limitations": ["dependent on issuing authority uploading documents", "limited offline access", "awareness/adoption gaps"]},
        {"name": "MyGov India", "description": "Citizen engagement platform for government initiatives, polls, and discussions.",
         "key_features": ["citizen polls", "discussion forums", "scheme information"],
         "limitations": ["engagement skews to specific demographics", "limited grievance-resolution tracking", "content is announcement-heavy"]},
        {"name": "Swachhata App", "description": "App for citizens to report sanitation/garbage issues to local municipal bodies.",
         "key_features": ["complaint reporting with photo/location", "status tracking"],
         "limitations": ["resolution speed depends on local body responsiveness", "limited to sanitation category", "adoption varies by city"]},
        {"name": "CoWIN", "description": "Vaccination registration and certificate platform built during COVID-19.",
         "key_features": ["slot booking", "digital certificates", "appointment scheduling"],
         "limitations": ["built for a specific campaign, not general healthcare scheduling", "high-traffic slot booking caused access issues", "narrow single-purpose scope"]},
    ],
    "Food & Nutrition": [
        {"name": "Zomato", "description": "Food delivery and restaurant-discovery app with reviews and ratings.",
         "key_features": ["restaurant discovery", "food delivery", "reviews"],
         "limitations": ["commission pressure on small restaurants", "quality-control complaints", "not nutrition-focused"]},
        {"name": "MyFitnessPal", "description": "Calorie and nutrition tracking app with a large food database.",
         "key_features": ["calorie tracking", "food database", "macro breakdown"],
         "limitations": ["database entries for regional/home-cooked dishes are inconsistent", "manual logging fatigue", "premium features paywalled"]},
        {"name": "Swiggy", "description": "Food delivery platform connecting users to local restaurants.",
         "key_features": ["restaurant ordering", "delivery tracking", "instant grocery (Instamart)"],
         "limitations": ["delivery-fee sensitivity among users", "restaurant partner margin pressure", "not focused on nutrition guidance"]},
        {"name": "HealthifyMe", "description": "AI-based diet and fitness coaching app with a calorie coach chatbot.",
         "key_features": ["AI diet coach", "calorie tracking", "trainer plans"],
         "limitations": ["premium coaching is paid", "photo-based food logging accuracy varies", "adherence drop-off over time"]},
        {"name": "BigBasket", "description": "Online grocery ordering platform with scheduled and express delivery.",
         "key_features": ["grocery catalog", "scheduled delivery", "subscriptions"],
         "limitations": ["delivery slot availability in peak hours", "quality-consistency complaints on perishables", "limited hyper-local sourcing transparency"]},
    ],
    "Real Estate & Housing": [
        {"name": "NoBroker", "description": "Brokerage-free platform for renting or buying property directly from owners.",
         "key_features": ["owner-direct listings", "no-brokerage model", "rental agreement services"],
         "limitations": ["listing verification challenges", "coverage concentrated in metro cities", "owner responsiveness varies"]},
        {"name": "99acres", "description": "Real-estate classifieds platform for buying, selling, and renting property.",
         "key_features": ["property listings", "price trends", "agent/owner filters"],
         "limitations": ["listing accuracy/duplication issues", "broker-heavy listings despite filters", "limited post-transaction support"]},
        {"name": "MagicBricks", "description": "Property portal for residential and commercial real estate search.",
         "key_features": ["property search", "locality insights", "loan assistance"],
         "limitations": ["similar broker-listing noise as competitors", "valuation accuracy varies by area", "limited tenant-verification tooling"]},
        {"name": "Housing.com", "description": "Real-estate search platform with map-based property discovery.",
         "key_features": ["map-based search", "verified listings tag", "EMI calculators"],
         "limitations": ["verification is self-declared, not always audited", "urban-focused inventory", "limited support for rental disputes"]},
    ],
    "Tourism & Travel": [
        {"name": "MakeMyTrip", "description": "Travel booking platform for flights, hotels, and holiday packages.",
         "key_features": ["flight/hotel booking", "holiday packages", "reviews"],
         "limitations": ["customer support responsiveness during disruptions", "dynamic pricing frustration", "limited hyper-local/off-beat itineraries"]},
        {"name": "TripAdvisor", "description": "Travel review and itinerary-planning platform for destinations and attractions.",
         "key_features": ["reviews/ratings", "itinerary planning", "booking links"],
         "limitations": ["review authenticity concerns", "not a direct booking engine itself", "content quality varies by destination"]},
        {"name": "Airbnb", "description": "Platform for booking short-term stays with local hosts.",
         "key_features": ["host listings", "reviews", "local experiences"],
         "limitations": ["trust/safety verification limits", "regulatory restrictions in some cities", "pricing surges during peak seasons"]},
        {"name": "OYO", "description": "Budget hotel aggregator standardizing quality across partner properties.",
         "key_features": ["budget hotel booking", "standardized amenities", "loyalty program"],
         "limitations": ["quality-consistency complaints across properties", "partner-hotel churn", "customer trust rebuilding after past controversies"]},
    ],
}


def get_domain_entries(domain):
    return KNOWLEDGE_BASE.get(domain, [])


def get_all_domains():
    return list(KNOWLEDGE_BASE.keys())
