"""Blueprint Exporter: multi-format export service (Markdown, JSON, DOCX)."""
import io
import json
from typing import Dict, Any, Optional
from modules.blueprint_export import build_blueprint_docx


class BlueprintExporter:
    """Exports unified project blueprints into structured Markdown, JSON, and DOCX."""

    @staticmethod
    def export_markdown(blueprint: Dict[str, Any], context: Optional[Dict[str, Any]] = None) -> str:
        """Export comprehensive markdown document detailing the full blueprint."""
        ctx = context or {}
        title = ctx.get("normalized_idea") or ctx.get("title") or "YosiFix Innovation Blueprint"
        domain = ctx.get("domain", "Technology")
        mutation = ctx.get("selected_mutation_detail", {})
        mutation_title = mutation.get("title") or blueprint.get("selected_mutation", "Standard Architecture")

        md_lines = [
            f"# {title}",
            f"> **Domain:** {domain} | **Strategic Mutation:** {mutation_title}",
            "",
            "## 1. Executive Summary",
            blueprint.get("executive_summary", "No executive summary provided."),
            "",
            f"**Elevator Pitch:** *\"{blueprint.get('elevator_pitch', '')}\"*",
            "",
            "## 2. Problem Statement & Market Opportunity",
            blueprint.get("verified_problem_statement", ctx.get("problem", "Verified market need.")),
            "",
            "### Target Users & Beneficiaries",
        ]

        target_users = blueprint.get("target_audience") or ctx.get("target_users") or []
        for user in target_users:
            md_lines.append(f"- {user}")

        md_lines.extend([
            "",
            "## 3. Core Innovation & Strategic Gap",
            blueprint.get("core_innovation_and_gap", "Novel approach tackling key market oversights."),
            "",
            "### Selected Strategic Pivot / Mutation",
            f"**{mutation_title}**",
            mutation.get("rationale", ""),
            "",
        ])

        mods = mutation.get("key_modifications", [])
        if mods:
            md_lines.append("#### Key Architectural Modifications:")
            for mod in mods:
                md_lines.append(f"- {mod}")
            md_lines.append("")

        # System Architecture & Diagram
        md_lines.extend([
            "## 4. System Architecture",
            blueprint.get("system_architecture_summary", "Modular, resilient architecture."),
            "",
        ])

        arch = ctx.get("architecture") or {}
        mermaid = arch.get("mermaid_diagram")
        if mermaid:
            md_lines.extend([
                "### Architectural Flow Diagram",
                "```mermaid",
                mermaid,
                "```",
                "",
            ])

        # Technology Stack
        tech = ctx.get("technology") or ctx.get("tech_stack") or {}
        stack = tech.get("recommended_stack") if isinstance(tech, dict) and "recommended_stack" in tech else tech
        if isinstance(stack, dict) and stack:
            md_lines.extend([
                "## 5. Technology Stack",
                "| Layer | Technology Choice | Rationale |",
                "| :--- | :--- | :--- |",
            ])
            for layer, tech_choice in stack.items():
                md_lines.append(f"| {layer} | {tech_choice} | High-throughput, edge-compatible |")
            md_lines.append("")

        # Execution Strategy & Roadmap
        md_lines.extend([
            "## 6. Execution Strategy & Delivery Roadmap",
            blueprint.get("execution_strategy", "Phased rollout starting with localized MVP."),
            "",
        ])

        roadmap = ctx.get("roadmap") or {}
        phases = roadmap.get("phases", []) if isinstance(roadmap, dict) else []
        for phase in phases:
            md_lines.append(f"### {phase.get('phase_name', 'Phase')} ({phase.get('duration_weeks', 2)} weeks)")
            md_lines.append(f"**Goal:** {phase.get('goal', 'Milestone completion')}")
            deliverables = phase.get("deliverables", [])
            for d in deliverables:
                md_lines.append(f"- [ ] {d}")
            md_lines.append("")

        # Judge Defense Strategy
        md_lines.extend([
            "## 7. Judge & Investor Defense Strategy",
            blueprint.get("judge_defense_summary", "Robust defensibility against market incumbents."),
            "",
            "---",
            "*Generated by YosiFix Evidence-Driven Innovation Operating System*",
        ])

        return "\n".join(md_lines)

    @staticmethod
    def export_json(blueprint: Dict[str, Any], context: Optional[Dict[str, Any]] = None) -> str:
        """Export raw structured JSON."""
        payload = {
            "blueprint": blueprint,
            "context": context or {},
            "version": "2.0",
        }
        return json.dumps(payload, indent=2)

    @staticmethod
    def export_docx_bytes(idea: Any, analysis: Any, prompts: Optional[Any] = None) -> io.BytesIO:
        """Export as python-docx buffer."""
        doc = build_blueprint_docx(idea, analysis, prompts)
        bio = io.BytesIO()
        doc.save(bio)
        bio.seek(0)
        return bio
